# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: XW's Recipes
email: wangxin19930411@163.com
author: Xin Wang
description: >- # this means to ignore newlines until "baseurl:"
    Nice to see you!
    Here is the place I will share my recipes.
baseurl: "/recipes" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  WangXin93
twitter_username: WangX93

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

logo: "logo.jpg"
show_downloads: false # indicate whether to provide a download URL]
google_analytics: G-SK8D857EXW

github:
  zip_url: https://github.com/WangXin93/recipes.git
  tar_url: https://github.com/WangXin93/recipes.git 
  repository_url: https://github.com/WangXin93/recipes

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
